modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/quinn-semele/expanded-storage/issues"
license = "See LICENSE file"

[[mods]]
modId = "expandedstorage"
version = "${version}"
displayName = "Expanded Storage"
authors = "Quinn Semele"
logoFile = "icon.png"
displayURL = "https://modrinth.com/mod/expanded-storage"
description = "A mod adding various storage types, including double iron chests."

[[dependencies.expandedstorage]]
modId = "forge"
mandatory = true
versionRange = "[43.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.expandedstorage]]
modId = "minecraft"
mandatory = true
versionRange = "1.19.2"
ordering = "NONE"
side = "BOTH"
