modLoader = "javafml"
loaderVersion = "[3,)"
issueTrackerURL = "https://github.com/quinn-semele/expanded-storage/issues"
license = "See LICENSE file"

[[mods]]
modId = "expandedstorage"
version = "${version}"
displayName = "Expanded Storage"
authors = "Quinn Semele"
logoFile = "icon.png"
displayURL = "https://modrinth.com/mod/expanded-storage"
description = "A mod adding various storage types, including double iron chests."

[[dependencies.expandedstorage]]
modId = "neoforge"
type = "required"
versionRange = "[20.5.0-alpha,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.expandedstorage]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.5-pre,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "expandedstorage-common.mixins.json"

[[mixins]]
config = "expandedstorage-forge.mixins.json"
