modLoader = "javafml"
loaderVersion = "[2,)"
license = "PolyForm-Shield-1.0.0, https://polyformproject.org/licenses/shield/1.0.0/"
issueTrackerURL = "https://github.com/quinn-semele/expanded-storage/issues/"

[[mods]]
modId = "stowage"
version = "${mod_version}"
displayName = "Stowage: Core"
displayURL = "https://modrinth.com/mod/expanded-storage/"
logoFile = "stowage.png"
authors = "Quinn Semele"

description = '''A storage mod focusing on user experience.'''

[modproperties.stowage]
stowagePluginClass = "semele.quinn.stowage.impl.CoreStowagePlugin"

[[dependencies.stowage]]
modId = "neoforge"
type = "required"
versionRange = "[20.5-alpha,20.6)"
ordering = "NONE"
side = "BOTH"

#[[dependencies.stowage]]
#modId = "minecraft"
#type = "required"
#versionRange = "[1.20.5,1.20.6)"
#ordering = "NONE"
#side = "BOTH"

[features.stowage]
javaVersion = "[21,)"
